using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using SplineMesh;
using Mirror;


[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class NetworkFollowSpline : MonoBehaviour
{
    public GameObject Follower;
    public float DurationInSecond;
    public float startOffset = 0;

    private float rate = 0;
    private float rateOffset = 0;
    private Spline spline;

    private GameObject generated;

    private void OnEnable()
    {
        rate = 0;
        string generatedName = "generated by " + GetType().Name;
        var generatedTranform = transform.Find(generatedName);
        generated = generatedTranform != null ? generatedTranform.gameObject : Instantiate(Follower, gameObject.transform);
        generated.name = generatedName;

        spline = GetComponent<Spline>();

#if UNITY_EDITOR
        //EditorApplication.update += Update;
#endif
    }

    void OnDisable()
    {
#if UNITY_EDITOR
        //EditorApplication.update -= Update;
#endif
    }

    void Update()
    {
        //having an rate offset variable to stay in range is a little silly, but it works fine
        rate = ((float)(NetworkTime.time + startOffset) / DurationInSecond) + rateOffset;

        while (rate > spline.nodes.Count - 1)
        {
            rateOffset -= spline.nodes.Count - 1;
            rate -= spline.nodes.Count - 1; //to fix this update only
        }
        PlaceFollower();
    }


    private void PlaceFollower()
    {
        if (generated != null)
        {
            CurveSample sample = spline.GetSample(rate);
            generated.transform.localPosition = sample.location;
            generated.transform.localRotation = sample.Rotation;
        }
    }
}


